apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  namespace: grupo4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
              - name: nginx
                image: juanig99/grupo4-tup:v1
                ports:
                        - containerPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx2
  namespace: grupo4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
              - name: nginx
                image: juanig99/grupo4-tup:v1
                ports:
                        - containerPort: 8000
